In [ ]:
"""
This notebook will fit Log Return Volatility vs Sentiment Scores
Goal is to detect regime change 
Use the scikit hidden markov model implementation!
"""

In [1]:
from Hidden_Markov_Model import HMM_Pipeline

num_of_regimes = 2
n_mix = 2
hmm_pipeline = HMM_Pipeline(num_of_regimes, n_mix)

In [2]:
import pandas as pd

df = pd.read_csv("./TickerData/merged_sentiment_ticker.csv")

In [7]:
sector = "Information Technology"
ticker = "XLK"

test_row = 60

train_df = df[:len(df)-test_row].loc[:, ["Date", sector, f"{ticker} Volatility"]]
test_df = df[len(df)-test_row:].loc[:, ["Date", sector, f"{ticker} Volatility"]]
num_of_iters = 100

results_df = hmm_pipeline.HMM_pipeline(sector, ticker, train_df, test_df, num_of_iters)

========================================
  State 0  (n=50)
========================================

Means:
Information Technology    0.284200
XLK Volatility            0.012223

Covariance Matrix:
                        Information Technology  XLK Volatility
Information Technology                0.092923       -0.000505
XLK Volatility                       -0.000505        0.000016

Correlation Matrix:
                        Information Technology  XLK Volatility
Information Technology                1.000000       -0.410307
XLK Volatility                       -0.410307        1.000000

========================================
  State 1  (n=10)
========================================

Means:
Information Technology    0.013000
XLK Volatility            0.020578

Covariance Matrix:
                        Information Technology  XLK Volatility
Information Technology                0.170046        0.001484
XLK Volatility                        0.001484        0.000042

Correlation Matrix:
                        Information Technology  XLK Volatility
Information Technology                1.000000        0.558441
XLK Volatility                        0.558441        1.000000

In [8]:
hmm_pipeline._Visualize_Results(results_df, sector, ticker)

In [ ]:
""" 
Look at the mean and variance of the vol. and sentiment scores and compared the stats for the 2 states

How do I know these distinctions are significant?
"""

In [4]:
results_df

           Date  Information Technology  XLK Volatility  Predicted States
100  2024-06-24                    0.15        0.014845                 1
101  2024-06-25                    0.67        0.015897                 1
102  2024-06-26                    0.58        0.015746                 1
103  2024-06-27                   -0.10        0.015287                 0
104  2024-06-28                    0.71        0.015298                 1
..          ...                     ...             ...               ...
511  2026-03-16                    0.15        0.012484                 0
512  2026-03-17                    0.55        0.012870                 1
513  2026-03-18                    0.20        0.013294                 0
514  2026-03-18                   -0.10        0.013294                 0
515  2026-03-20                   -0.25        0.014827                 0

[416 rows x 4 columns]

In [2]:
df

,Date,Information Technology,Health Care,Financials,Consumer Discretionary,Communication Services,Industrials,Consumer Staples,Energy,Utilities,...,XLI Volatility,XLK Closing Price,XLK Log Return,XLK Volatility,XLB Closing Price,XLB Log Return,XLB Volatility,XLRE Closing Price,XLRE Log Return,XLRE Volatility
0,2024-01-22,0.75,0.45,0.25,0.40,0.50,0.20,0.35,0.15,0.10,...,0.010095,99.098984,0.004387,0.011947,39.533054,0.002914,0.006685,36.065884,0.004641,0.010936
1,2024-01-23,0.62,0.18,0.74,0.56,0.68,0.31,0.12,-0.08,0.05,...,0.007876,99.498222,0.004021,0.011758,39.662483,0.003269,0.004518,35.871078,-0.005416,0.010898
2,2024-01-24,0.45,0.22,0.33,0.32,0.44,0.37,0.18,0.41,0.29,...,0.007679,100.183365,0.006862,0.009070,39.125599,-0.013629,0.007310,35.379444,-0.013800,0.009348
3,2024-01-24,0.84,0.05,0.08,0.48,0.82,0.14,0.12,-0.18,0.02,...,0.007679,100.183365,0.006862,0.009070,39.125599,-0.013629,0.007310,35.379444,-0.013800,0.009348
4,2024-01-25,0.20,0.08,0.18,-0.08,0.12,-0.22,0.02,0.15,0.04,...,0.006631,100.602348,0.004173,0.008101,39.537849,0.010481,0.008839,35.861801,0.013542,0.011206
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511,2026-03-16,0.15,0.05,-0.35,-0.10,0.10,-0.15,0.05,0.85,0.00,...,0.012263,138.607666,0.014370,0.012484,49.181286,0.004260,0.005100,42.295715,0.007780,0.007673
512,2026-03-17,0.55,0.10,-0.20,0.35,0.25,-0.05,-0.10,0.75,-0.05,...,0.012842,139.366714,0.005461,0.012870,49.300755,0.002426,0.005540,42.434780,0.003283,0.008022
513,2026-03-18,0.20,-0.05,-0.15,-0.10,0.15,0.10,-0.35,0.85,-0.05,...,0.012924,137.788681,-0.011387,0.013294,48.265358,-0.021225,0.010369,41.739452,-0.016522,0.009680
514,2026-03-18,-0.10,-0.05,-0.20,-0.35,-0.05,-0.25,-0.15,0.65,-0.15,...,0.012924,137.788681,-0.011387,0.013294,48.265358,-0.021225,0.010369,41.739452,-0.016522,0.009680
515,2026-03-20,-0.25,0.05,-0.15,-0.35,0.05,-0.10,0.10,0.90,0.10,...,0.009192,135.121994,-0.022944,0.014827,46.771999,-0.016048,0.011684,40.319000,-0.032241,0.016341

In [3]:
df.columns

Index(['Date', 'Information Technology', 'Health Care', 'Financials',
       'Consumer Discretionary', 'Communication Services', 'Industrials',
       'Consumer Staples', 'Energy', 'Utilities', 'Real Estate', 'Materials',
       'XLC Closing Price', 'XLC Log Return', 'XLC Volatility',
       'XLY Closing Price', 'XLY Log Return', 'XLY Volatility',
       'XLP Closing Price', 'XLP Log Return', 'XLP Volatility',
       'XLE Closing Price', 'XLE Log Return', 'XLE Volatility',
       'XLF Closing Price', 'XLF Log Return', 'XLF Volatility',
       'XLV Closing Price', 'XLV Log Return', 'XLV Volatility',
       'XLI Closing Price', 'XLI Log Return', 'XLI Volatility',
       'XLK Closing Price', 'XLK Log Return', 'XLK Volatility',
       'XLB Closing Price', 'XLB Log Return', 'XLB Volatility',
       'XLRE Closing Price', 'XLRE Log Return', 'XLRE Volatility'],
      dtype='object')

In [ ]:
"""  
Look at how the regime classifications are affected by a rolling window of training
data , increasing window of training data, 
"""

In [ ]:
""" 
How would I compare different models , their similarities in order
to eval. the rolling window of data, different fits, etc.
"""